#!/bin/bash
#SBATCH --job-name alphafold
#SBATCH --mail-user=<your_email>
#SBATCH --partition general
#SBATCH --Nodes 1
#SBATCH --ntasks 1
#SBATCH --cpus-per-task 64
#SBATCH --time 1:00:00

module load localcolabfold

INPUT_FILE_PATH=/path/to/input.fasta
now=$(date +"%m_%d_%H_%M_%S")
OUTPUTDIR=$SLURM_SUBMIT_DIR/$SLURM_JOB_NAME-$now

mkdir -p $OUTPUTDIR

cd $SLURM_SUBMIT_DIR

srun colabfold_batch $INPUT_FILE_PATH $OUTPUTDIR