#!/bin/bash

#PBS -N my_r_job
#PBS -l walltime=48:00:00
#PBS -l nodes=1:ppn=8
#PBS -j oe
#PBS -V
#PBS -m abe
#PBS -M my_name@unm.edu

cd $PBS_O_WORKDIR

module load r-3.6.0-gcc-7.3.0-python2-7akol5t

Rscript my_script.R