#!/bin/bash

#SBATCH --job-name=source_separation

#SBATCH --output=/checkpoint/%u/jobs/%x/%j.out

#SBATCH --error=/checkpoint/%u/jobs/%x/%j.err

#SBATCH --nodes=1

#SBATCH --ntasks-per-node=2

#SBATCH --cpus-per-task=8

#SBATCH --mem-per-cpu=16G

#SBATCH --gpus-per-node=2

num_speakers=2
this_dir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" >/dev/null 2>&1 && pwd )"
exp_dir="/checkpoint/${USER}/exp/"
root_dir="/dataset/" # The directory where the directory ``Libri2Mix`` or ``Libri3Mix`` is stored.
num_gpu=2 # The number of GPUs used on one node.
num_node=1 # The number of nodes used on the cluster.
batch_size=6 # The batch size per GPU.


mkdir -p "${exp_dir}"

python -u \
  "${this_dir}/lightning_train.py" \
  --num-speakers "${num_speakers}" \
  --sample-rate 8000 \
  --root-dir "${root_dir}" \
  --exp-dir "${exp_dir}" \
  --num-gpu ${num_gpu} \
  --num-node ${num_node} \
  --batch-size ${batch_size} \