#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 32       # 32 cores (8 cores per GPU)
#$ -l h_rt=1:0:0    # 1 hour runtime (required to run on the short queue)
#$ -l gpu=4         # request 4 GPUs
#$ -l exclusive     # request exclusive access

./run_code.sh