#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 16       # 16 cores (8 cores per GPU)
#$ -l h_rt=240:0:0  # 240 hours runtime
#$ -l h_vmem=11G    # 11 * 16 = 176G total RAM
#$ -l gpu=2         # request 2 GPUs

./run_code.sh