#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G

# Load Python module
module load python

# Activate virtualenv
source <envname>/bin/activate

# Run Python script
python example.py