#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load annovar

convert2annovar.pl -format vcf4 \
                   -outfile example.out \
                   example.vcf