#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=4G

module load bamtools

bamtools convert -format fastq \
                 -in input_alignments.bam \
                 -out output_reads.fastq