#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 4
#$ -l h_rt=240:0:0
#$ -l h_vmem=5G

module load bismark

# Fork the Bowtie2 aligner by half the number of cores requested
# to avoid poor performance and threading issues
REPCORES=$((NSLOTS / 2))

bismark \
    --genome_folder <genome_folder> \
    -1 fasta1.fq.gz \
    -2 fasta2.fq.gz \
    -p ${REPCORES}