#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 4
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load blast+

blastn -num_threads ${NSLOTS} \
       -out blast_serial.tsv \
       -outfmt 6 \
       -db /data/PublicDataSets/shared_dbs/nt/2023-02-21/nt \
       -query GRCh38_chr1_1percent.fasta