#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load miniforge
mamba activate muscle_env

muscle -align sequences.fasta \
       -output alignment.fasta \
       -threads ${NSLOTS}