#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load phylobayesmpi

mpirun -np ${NSLOTS} pb_mpi \
   -d test.puz \
   -t test.tre \
   -x 5 20 \
   test