#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load qctool

qctool -g cohort1.bgen -s cohort1.sample -g cohort2.bgen -s \
          cohort2.sample -og joined.gen -os joined.sample