#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load miniforge
mamba activate quast_env

quast -r reference.fasta.gz \
      -g genes.gff \
      -t ${NSLOTS} \
      testcontigs_1.fasta \
      testcontigs_2.fasta