#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load raxml

raxmlHPC-MPI-AVX -m BINGAMMA \
                 -p 12345 \
                 -s ~/raw_data.phy \
                 -n raxml_output_file \
                 -N ${NSLOTS}