#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load raxml-ng-mpi

mpirun -np ${NSLOTS} \
  raxml-ng-mpi \
    --parse \
    --msa input_file.phy \
    --model GTR+G \
    --prefix T2