#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load relion

relion_refine --angpix 1 \
              --i example.mrcs \
              --iter 5 \
              --j ${NSLOTS} \
              --o output