#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load relion

mpirun -np ${NSLOTS} relion_refine_mpi \
  -x LD_LIBRARY_PATH \
  --angpix 1 \
  --i preprocessed.mrcs \
  --iter 2 \
  --o test