#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 2
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G

module load miniforge
mamba activate rsem_env

# Convert a transcript coordinate BAM alignments file into a genomic
# coordinate BAM alignments file
rsem-tbam2gbam reference_name \
               unsorted_transcript_bam_input \
               genome_bam_output \
               -p ${NSLOTS}