#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=1G

module load salmon

salmon index -t transcripts.fasta \
             -i transcripts_index \
             -p ${NSLOTS}

salmon quant -i transcripts_index \
             -l A \
             -1 file1.fastq \
             -2 file2.fastq \
             --validateMappings \
             -o transcripts_quant \
             -p ${NSLOTS}