#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 1
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G

module load sra-tools

# Produces gzip’d output file with a reconstructed header.
sam-dump -r --gzip --output-file output-file.sam.gz input-file