#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 2
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G

module load star

# Genome indexing
STAR --runMode genomeGenerate \
     --genomeDir <input_fasta_dir> \
     --genomeFastaFiles <input_fasta> \
     --runThreadN ${NSLOTS}

# Genome alignment
STAR --runMode alignReads \
     --genomeDir <input_fasta_dir> \
     --readFilesIn <input_file(s)> \
     --runThreadN ${NSLOTS}