#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 2
#$ -l h_rt=1:0:0
#$ -l h_vmem=2G

module load trimmomatic

trimmomatic PE input_forward.fq.gz input_reverse.fq.gz \
               output_forward_paired.fq.gz output_forward_unpaired.fq.gz \
               output_reverse_paired.fq.gz output_reverse_unpaired.fq.gz \
               ILLUMINACLIP:TruSeq3-PE.fa:2:30:10:2:True \
               LEADING:3 TRAILING:3 MINLEN:36 \
               -threads ${NSLOTS}