#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load openmolcas

# Instruct the scheduler to spawn pymolcas processes on all execution
# hosts granted for the job.
export I_MPI_HYDRA_BOOTSTRAP=sge

pymolcas -np ${NSLOTS} example.input