#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe parallel 96
#$ -l infiniband=ddy-i
#$ -l h_rt=240:0:0

module load miniforge
mamba activate qe_env

export ESPRESSO_TMPDIR=${TMPDIR}
mpirun -np ${NSLOTS} pw.x < qe.in