#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=240:0:0
#$ -l h_vmem=11G
#$ -l gpu=1
#$ -l ansys=12

module load ansys
export NUM_GPU_DEVICES=`echo $SGE_HGR_gpu | wc -w`
fluent 3d -g -rsh -t$NSLOTS -gpgpu=$NUM_GPU_DEVICES -i SIM-FILE