#!/bin/bash
#SBATCH --job-name=train
#SBATCH --output=train_%j.out
#SBATCH --error=train_%j.err
#SBATCH --gpus-per-node=8
#SBATCH --ntasks-per-node=8
#SBATCH -N 4
#SBATCH --cpus-per-task=10

srun python train.py --dataset-path ./exp/data/mfcc/ --exp-dir ./exp_iter1 --feature-type mfcc --num-class 100 --max-updates 250000 --learning-rate 0.0005