#!/bin/bash
#SBATCH --cpus-per-task=12
#SBATCH --gpus-per-node=8
#SBATCH -N 4
#SBATCH --ntasks-per-node=8

srun python train.py --exp-dir ./experiments --librispeech-path ./librispeech/ --global-stats-path ./global_stats.json --sp-model-path ./spm_unigram_1023.model --epochs 160