#!/bin/bash -l
#SBATCH --job-name=job-array-example
#SBATCH --time=1:0:0
#SBATCH --array=1-100%10  # Job array from task ID 1 to 100, with a step size of 10
#SBATCH --ntasks-per-node=1
#SBATCH --partition=shared
#SBATCH --mail-type=end
#SBATCH --mail-user=userid@jhu.edu
#SBATCH --reservation=Training

ml intel/2022.2

#Your executable or script goes here
#Example: Running a Python script
python my_script.py $SLURM_ARRAY_TASK_ID

#In this example, each job instance will execute the script with a different SLURM_ARRAY_TASK_ID