#!/bin/bash
#$ -cwd
#$ -j y
#$ -pe smp 8
#$ -l h_rt=240:0:0
#$ -l h_vmem=11G
#$ -l gpu=1

module load colmap

# Set the path to your dataset
export DATASET_PATH=/path/to/dataset

colmap automatic_reconstructor \
  --workspace_path "${DATASET_PATH}" \
  --image_path "${DATASET_PATH}/images" \
  --num_threads "${NSLOTS}" \
  --gpu_index 0