#!/bin/bash -l
#SBATCH --job-name=llmTest_job
#Project account
#SBATCH --account=nnxxxx
#SBATCH --output=output_test.log
#SBATCH --error=error_test.log

#SBATCH --time=0:30:00
#SBATCH --partition=accel
#SBATCH --ntasks=1
#SBATCH --cpus-per-task=1
#SBATCH --mem=10G
#SBATCH --gpus=1
## Set up job environment:
set -o errexit  # Exit the script on any error
set -o nounset  # Treat any unset variables as an error
module --quiet purge  # Reset the modules to the system default
module load Python/3.11.5-GCCcore-13.2.0  # Load the Python module
module list  # List loaded modules for debugging

#directory where the program is located
cd /cluster/work/users/your_user_name/llmTest

#create and  Activate virtual environment
python -m venv myenv
source myenv/bin/activate

#Install packages from requirements.txt
pip install -r requirements.txt

# Start GPU monitoring in the background
nvidia-smi --query-gpu=timestamp,utilization.gpu,utilization.memory --format=csv -l 1 > gpu_usage.csv & 
GPU_MONITOR_PID=$!


# Run the script
python seamless.py

#Stop GPU monitoring
kill $GPU_MONITOR_PID