#!/bin/sh
#PJM -L "node=1"
#PJM -L "rscgrp=small"
#PJM -L "elapse=6:00:00"
#PJM -x PJM_LLIO_GFSCACHE=/RAvG7tRc8R3QSe+OEfBL9Q==
#PJM -s
#PJM -j
#

umask 0002
. setup-env.sh

#
#spack install py-horovod %fj frameworks=pytorch
spack install py-horovod@0.26.1 %fj tensor_ops=mpi frameworks=pytorch ^py-torch~cuda+mkldnn ^rust/tvwkavecgt

